# Generated by Django 5.2.5 on 2025-12-12 10:25

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_blog_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internship',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Internship', 'verbose_name_plural': 'Internships'},
        ),
        migrations.RenameField(
            model_name='internship',
            old_name='timeStamp',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='blogimage',
            name='title',
            field=models.CharField(default='Untitled', max_length=200),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.upload_to_original),
        ),
    ]
