# Generated by Django 5.2.5 on 2025-12-14 06:18

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_blogimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='blogimage',
            options={'verbose_name': 'Blog Extra Image', 'verbose_name_plural': 'Blog Extra Images'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.AlterModelOptions(
            name='internship',
            options={},
        ),
        migrations.AlterField(
            model_name='blog',
            name='author_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.upload_to_uuid),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.upload_to_uuid),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='title',
            field=models.CharField(blank=True, default='Untitled', max_length=200),
        ),
        migrations.AlterField(
            model_name='internship',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='internship',
            name='offer_status',
            field=models.CharField(max_length=20),
        ),
    ]
