# Generated by Django 5.2.5 on 2025-12-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_blog_options_alter_blogimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimage',
            name='position',
            field=models.PositiveIntegerField(default=1, help_text='Paragraph number after which this image should appear (1 = after first paragraph).'),
        ),
    ]
