# Generated by Django 5.2.5 on 2025-12-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_blogimage_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Paragraph number after which the image appears'),
        ),
    ]
