# Generated by Django 5.2.5 on 2025-12-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_blogimage_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogimage',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Blog Extra Image', 'verbose_name_plural': 'Blog Extra Images'},
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Paragraph index after which this image appears'),
        ),
    ]
