# Generated by Django 5.2.5 on 2025-12-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_blogimage_options_alter_blogimage_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogimage',
            options={'ordering': ['position'], 'verbose_name': 'Blog Extra Image', 'verbose_name_plural': 'Blog Extra Images'},
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
